# Generated by Django 3.1.7 on 2021-03-23 11:47

from django.db import migrations, models
import workspace.models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_auto_20210318_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='pathname',
        ),
        migrations.AddField(
            model_name='folder',
            name='files',
            field=models.FileField(
                default='testing', upload_to=workspace.models.user_directory_path),
            preserve_default=False,
        ),
    ]
