# Generated by Django 3.1.7 on 2021-03-23 14:59

from django.db import migrations, models
import django.db.models.deletion
import workspace.models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_auto_20210323_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='files',
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=100)),
                ('filename', models.FileField(upload_to=workspace.models.user_directory_path)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.folder')),
            ],
        ),
    ]
